config/routes.rb
InventorySystem::Application.routes.draw do
  root 'foods#index'
  resources :foods

end

app/models/food.rb
class Food < ActiveRecord::Base
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :description
  validates_presence_of :quantity
  validates_numericality_of :quantity

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food item added successfully'
    else
      render :new
    end
  end



  private
  def food_params
    params.require(:food).permit(:title, :description, :quantity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_items/_food_item_form.html.erb
<%= form_for(@food_item) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>


<% end %>

app/views/foods/_food_form.html.erb
<%= form_for(@food) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label :quantity %> <br>
  <%= f.text_field :quantity %> <br>

  <%= f.submit 'Submit' %>


<% end %>

app/views/foods/index.html.erb
<h1>Food List</h1>

<% @foods.each do |food| %>
  <%= food.title %>
  <%= food.description %>
  <%= food.quantity %>
<% end %>

<%= link_to 'Add Food Item', new_food_path %>

app/views/foods/new.html.erb
<% if @food.errors.full_messages.any? %>
  <% @food.errors.full_messages.each do |error_message| %>
    <%= error_message %> <br>
  <% end %>
<% end %>

<%= render 'food_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventorySystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <%= msg %> <br>
<% end %>

<%= yield %>


</body>
</html>